version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db_name
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
